# -- config path
config_dir : '_base_/custom'
config_file : 'custom_config'

## -- wandb
wandb : True
wandb_proj : 'Semantic Segmentation'
wandb_name : 'uperswin_512_512'
log_interval : 50

# -- hyperparameter
seed : 84
batch_size : 8
lr : 0.00006

# -- validation
validate : True
eval_interval : 2000

# -- checkpoint
use_ckpt : True
ckpt_name : 'upernet_swin_base_patch4_window7_512x512'

## -- save best model
save_best_model : True

data_dir_root : '/opt/ml/input/mmseg'

